### ISSUE TITLE
Check string connection parameters

### ISSUE THREAD

**Issue by marcobambini** [sqlitecloud/sqlitecloud-go#5]
See https://github.com/sqlitecloud/sqlitecloud-js/issues/68#issuecomment-2055450382

**Comment by danielebriggi** [comment]
- [x] timeout: (integer >= 0) client connection timeout parameter (in seconds)
        client socket option
- [x] compression: (1 or 0) set if client supports LZ4 compression
        SET CLIENT KEY COMPRESSION TO 1;
- [x] zerotext: (1 or 0) flag to tell the server to zero-terminate strings
        SET CLIENT KEY ZEROTEXT TO 1;
- [x] memory: (1 or 0) flag to force the database to be in-memory
        database name is set to :memory:
- [x] create: (1 or 0) flag to force the creation of the database (if it does not exist)
        database name is used in CREATE DATABASE dbname IF NOT EXISTS
- [x] insecure: (1 or 0) flag to disable TLS
        client socket option
- [x] non_linearizable/nonlinearizable: (1 or 0) flag to request for immediate responses from the server node without waiting for linerizability guarantees
        SET CLIENT KEY NONLINEARIZABLE TO 1;
- [x] no_verify_certificate: (1 or 0) flag to accept invalid TLS certificates
        client socket option
- [ ] root_certificate: (string) full path to TLS root certificate
        client socket option
- [ ] client_certificate: (string) full path to TLS client certificate
        client socket 
- [ ] client_certificate_key: (string) full path to TLS client certificate key
        client socket 
- [x] noblob: (1 or 0) flag to tell the server to not send BLOB columns in rowsets
        SET CLIENT KEY NOBLOB TO 1;
- [x] maxdata: (integer >= 0) value to tell the server to not send columns with more than max_data bytes
        SET CLIENT KEY MAXDATA TO 1;
- [x] maxrows: (integer >= 0) value to control rowset chunks based on the number of rows
        SET CLIENT KEY MAXROWS TO 1;
- [x] maxrowset: (integer >= 0) value to control the maximum allowed size for a rowset
        SET CLIENT KEY MAXROWSET TO 1;
- [x] apikey: (string) apikey value used for authentication (instead of username/password)
        AUTH APIKEY value;

**Comment by danielebriggi** [comment]
With @andinux we considered no more useful the parameters for clients certificates
